/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavesIndexRouteImport } from './routes/saves/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as SavesSaveIdIndexRouteImport } from './routes/saves/$saveId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SavesSaveIdRoutesIndexRouteImport } from './routes/saves/$saveId/routes/index'
import { Route as SavesSaveIdRoutesRouteIdIndexRouteImport } from './routes/saves/$saveId/routes/$routeId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesIndexRoute = SavesIndexRouteImport.update({
  id: '/saves/',
  path: '/saves/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesSaveIdIndexRoute = SavesSaveIdIndexRouteImport.update({
  id: '/saves/$saveId/',
  path: '/saves/$saveId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesSaveIdRoutesIndexRoute = SavesSaveIdRoutesIndexRouteImport.update({
  id: '/saves/$saveId/routes/',
  path: '/saves/$saveId/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesSaveIdRoutesRouteIdIndexRoute =
  SavesSaveIdRoutesRouteIdIndexRouteImport.update({
    id: '/saves/$saveId/routes/$routeId/',
    path: '/saves/$saveId/routes/$routeId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/saves/': typeof SavesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/saves/$saveId/': typeof SavesSaveIdIndexRoute
  '/saves/$saveId/routes/': typeof SavesSaveIdRoutesIndexRoute
  '/saves/$saveId/routes/$routeId/': typeof SavesSaveIdRoutesRouteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/saves': typeof SavesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/saves/$saveId': typeof SavesSaveIdIndexRoute
  '/saves/$saveId/routes': typeof SavesSaveIdRoutesIndexRoute
  '/saves/$saveId/routes/$routeId': typeof SavesSaveIdRoutesRouteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/saves/': typeof SavesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/saves/$saveId/': typeof SavesSaveIdIndexRoute
  '/saves/$saveId/routes/': typeof SavesSaveIdRoutesIndexRoute
  '/saves/$saveId/routes/$routeId/': typeof SavesSaveIdRoutesRouteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/saves/'
    | '/api/auth/$'
    | '/saves/$saveId/'
    | '/saves/$saveId/routes/'
    | '/saves/$saveId/routes/$routeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/saves'
    | '/api/auth/$'
    | '/saves/$saveId'
    | '/saves/$saveId/routes'
    | '/saves/$saveId/routes/$routeId'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/saves/'
    | '/api/auth/$'
    | '/saves/$saveId/'
    | '/saves/$saveId/routes/'
    | '/saves/$saveId/routes/$routeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  SavesIndexRoute: typeof SavesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SavesSaveIdIndexRoute: typeof SavesSaveIdIndexRoute
  SavesSaveIdRoutesIndexRoute: typeof SavesSaveIdRoutesIndexRoute
  SavesSaveIdRoutesRouteIdIndexRoute: typeof SavesSaveIdRoutesRouteIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves/': {
      id: '/saves/'
      path: '/saves'
      fullPath: '/saves/'
      preLoaderRoute: typeof SavesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves/$saveId/': {
      id: '/saves/$saveId/'
      path: '/saves/$saveId'
      fullPath: '/saves/$saveId/'
      preLoaderRoute: typeof SavesSaveIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves/$saveId/routes/': {
      id: '/saves/$saveId/routes/'
      path: '/saves/$saveId/routes'
      fullPath: '/saves/$saveId/routes/'
      preLoaderRoute: typeof SavesSaveIdRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves/$saveId/routes/$routeId/': {
      id: '/saves/$saveId/routes/$routeId/'
      path: '/saves/$saveId/routes/$routeId'
      fullPath: '/saves/$saveId/routes/$routeId/'
      preLoaderRoute: typeof SavesSaveIdRoutesRouteIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  SavesIndexRoute: SavesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SavesSaveIdIndexRoute: SavesSaveIdIndexRoute,
  SavesSaveIdRoutesIndexRoute: SavesSaveIdRoutesIndexRoute,
  SavesSaveIdRoutesRouteIdIndexRoute: SavesSaveIdRoutesRouteIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
